# Generated by Django 3.2.12 on 2022-04-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clienteid',
            fields=[
                ('cliente_id', models.TextField(primary_key=True, serialize=False)),
                ('secret', models.TextField()),
            ],
            options={
                'ordering': ['-cliente_id'],
            },
        ),
        migrations.CreateModel(
            name='ClientePessoaNatural',
            fields=[
                ('cliente_id', models.TextField(primary_key=True, serialize=False)),
                ('nome_civil', models.TextField()),
                ('nome_social', models.TextField()),
                ('nome_marca', models.TextField()),
                ('nome_razaosocial', models.TextField()),
                ('cpf', models.IntegerField()),
                ('cnpj', models.IntegerField()),
                ('estado_civil', models.TextField()),
                ('sexo', models.TextField()),
                ('nacionalidade', models.TextField()),
                ('data_nascimento', models.DateField()),
            ],
            options={
                'ordering': ['-cliente_id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoValorCredito',
            fields=[
                ('cliente_id', models.TextField(primary_key=True, serialize=False)),
                ('valor_cliente', models.FloatField()),
                ('credito_cliente', models.FloatField()),
                ('data_consulta', models.DateField()),
            ],
            options={
                'ordering': ['-cliente_id'],
            },
        ),
        migrations.CreateModel(
            name='PropostaCredito',
            fields=[
                ('cliente_id', models.TextField(primary_key=True, serialize=False)),
                ('credito_cliente', models.FloatField()),
                ('credito_recomendado', models.FloatField()),
                ('credito_preaprov', models.FloatField()),
                ('credito_limite', models.FloatField()),
            ],
            options={
                'ordering': ['-cliente_id'],
            },
        ),
        migrations.CreateModel(
            name='ValorCliente',
            fields=[
                ('cliente_id', models.TextField(primary_key=True, serialize=False)),
                ('renda_fixa', models.FloatField()),
                ('data_renda', models.DateField()),
                ('creditcard_valorfaturapg', models.FloatField()),
                ('data_creditcard', models.DateField()),
                ('contacorrente', models.TextField()),
                ('data_contacorrente', models.TextField()),
                ('contapoupanca', models.TextField()),
                ('data_contapoupanca', models.DateField()),
                ('valor_financiamento', models.FloatField()),
                ('valor_parcela_financiamento', models.FloatField()),
                ('data_inicio_financ_contrato', models.DateField()),
                ('data_fim_financ_contrato', models.DateField()),
                ('valor_emprestimo', models.FloatField()),
                ('valor_parcela_emprestimo', models.FloatField()),
                ('data_inicio_emprest_contrato', models.DateField()),
                ('data_fim_emprest_contrato', models.DateField()),
                ('patrimonios', models.FloatField()),
                ('data_patrimonios', models.DateField()),
                ('data_consulta', models.DateField()),
            ],
            options={
                'ordering': ['-cliente_id'],
            },
        ),
        migrations.CreateModel(
            name='ValorClienteConjunto',
            fields=[
                ('clienteconjunto_id', models.TextField(primary_key=True, serialize=False)),
                ('cliente_id', models.TextField()),
                ('cliente_id2', models.TextField()),
                ('renda_fixa', models.FloatField()),
                ('data_renda', models.DateField()),
                ('creditcard_valorfaturapg', models.FloatField()),
                ('data_creditcard', models.DateField()),
                ('contacorrente', models.TextField()),
                ('data_contacorrente', models.TextField()),
                ('contapoupanca', models.TextField()),
                ('data_contapoupanca', models.DateField()),
                ('valor_financiamento', models.FloatField()),
                ('valor_parcela_financiamento', models.FloatField()),
                ('data_inicio_financ_contrato', models.DateField()),
                ('data_fim_financ_contrato', models.DateField()),
                ('valor_emprestimo', models.FloatField()),
                ('valor_parcela_emprestimo', models.FloatField()),
                ('data_inicio_emprest_contrato', models.DateField()),
                ('data_fim_emprest_contrato', models.DateField()),
                ('patrimonios', models.FloatField()),
                ('data_patrimonios', models.DateField()),
                ('data_consulta', models.DateField()),
            ],
            options={
                'ordering': ['-cliente_id'],
            },
        ),
    ]
